title: Durable Knowledge Bases & Memory Systems
description: >-
  A library for creating knowledge bases that are durable, scalable, and
  intuitive. Ethan Porter's submission to the Future of Life Foundation's
  Epistack Competition.
theme: jekyll-theme-primer
